# engines/query_budget.py

QUERY_LIMITS = {
    "SKU_RECONCILIATION": 1,
    "DISTRIBUTOR_HEALTH_DETAIL": 1,
    "SUPPLIER_CONCENTRATION": 2,
    "CAPACITY_CERTIFICATION": 1,
    "QA_INSPECTION_CERT": 1,
    "CSR_BUDGET_EXECUTION": 1,
    "INSURANCE_AUDIT_MISMATCH": 1,
    "UNDEFINED_JARGON": 1,
    "MEASUREMENT_UNIT_CONSISTENCY": 1,
    "REVENUE_CHANNEL_BIFURCATION": 1,
    "TRADEMARK_COVERAGE_GAP": 2,
    "OPERATIONAL_SCRAP": 1
}
